import React from "react";
import { useRouter } from "next/router";
import Head from "next/head";

const Cards = () => {
    const router = useRouter();
    const { id } = router.query;

    return (
        <>
            <Head>
                <title>Natnael Engeda</title>
                <meta name="description" content="Generated By Alamondai" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                
            </main>
        </>
    );
}

export default Cards;