// import React from "react";
// import { useRouter } from "next/router";
// import Head from "next/head";
// import Image from "next/image";


// import ProfileImage from "./components/ProfileImage";
// import PersonalInfo from "./components/PersonalInfo";
// import Social from "./components/Social";
// import Contact from "./components/Contact";
// import Shop from "./components/Shop";
// import Work from "./components/Work";
// import Footer from "./components/Footer";
// import Project from "./components/Project";
// import Message from "./components/Message";

// const Cards = () => {
//     const router = useRouter();
//     const { id } = router.query;  

//     return (
//         <>
//             <Head>
//                 <title>Natnael Engeda</title>
//                 <meta name="description" content="Generated By Alamondai" />
//                 <meta name="viewport" content="width=device-width, initial-scale=1" />
//                 <link rel="icon" href="/favicon.ico" />
//             </Head>
//             <main className="flex flex-col w-full bg-slate-700 min-h-screen lg:w-[360px] lg:mx-auto">
//                 <ProfileImage />

//                 <section className="flex flex-col items-center py-5">
//                     <PersonalInfo />
//                     <Social />

//                     <div className="w-full px-5">
//                         <hr className="white" />
//                     </div>

//                 </section>

//                 <section className="flex flex-col gap-8 w-full bg-white px-5 min-h-screen py-5 ">
//                     <Contact />

//                     <hr className="text-black bg-black border border-black rounded-full w-5/6 mx-auto" />

//                     <section className="flex flex-col gap-4 flex-wrap">
//                         {/* Shops */}
//                         <Shop />

//                         {/* Work */}
//                         <Work/>

//                         {/* Project */}
//                         <Project/>

//                         {/* Message */}
//                         <Message/>
                        
//                     </section>
//                 </section>

//               <Footer/>
//             </main>
//         </>
//     );
// }

// export default Cards;

const CCC = () => {
    return ( 
        <div>
            
        </div>
     );
}
 
export default CCC;