import React from "react";
import { useRouter } from "next/router";
import Head from "next/head";
import Image from "next/image";


import ProfileImage from "./components/ProfileImage";
import PersonalInfo from "./components/PersonalInfo";
import Social from "./components/Social";
import Contact from "./components/Contact";
import Shop from "./components/Shop";
import Work from "./components/Work";
import Footer from "./components/Footer";
import Project from "./components/Project";
import Message from "./components/Message";

// Images
import placeholder from '../../assets/images/placeholder/placeholder.png';
import image from '../../assets/images/placeholder/placeholder.png'

const Yonas = () => {
    const router = useRouter();
    const skill = [1, 2, 3, 4, 5, 6];


    const myLoader = ({ src, width, quality }) => {
        return `${src}?w=${width}&q=${quality || 75}`
    }


    return (
        <>
            <Head>
                <title>Grima Atlabachew</title>
                <meta name="description" content="Generated By Alamondai" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex flex-col w-full bg-slate-700 min-h-screen container mx-auto">
                {/* <ProfileImage /> */}

                <section className="flex flex-col items-start justify-center py-1 px-10 gap-10 min-h-screen">
                    <div className="flex flex-col gap-10">
                        <div className="flex flex-col gap-2 md:gap-5">
                            <h1 className="text-3xl md:text-6xl text-white">Sanitary Systems and Elector Mechanical System Contractor</h1>
                            <hr className="w-1/3" />
                        </div>
                        <div className="flex flex-col gap-2 md:gap-5">
                            <p className="text-2xl md:text-4xl text-white">Grima Atlabachew</p>
                            <hr className="w-1/3" />
                        </div>
                    </div>


                </section>

                <section className="flex flex-col gap-8 w-full bg-white px-5 min-h-screen py-5 ">
                    <Contact />

                    <hr className="text-black bg-black border border-black rounded-full w-5/6 mx-auto" />

                    <section className="flex flex-col gap-6">
                        <div className="flex flex-col gap-3 items-center">
                            <h1 className="text-3xl md:text-5xl text-black">What I do</h1>
                            <hr className="w-1/6 text-red-800 border-2 border-red-800" />
                        </div>
                        <div className="grid grid-cols-2 lg:grid-cols-3 gap-10 px-5 md:px-20">
                            {
                                skill.map((items) => (
                                    <div className="flex flex-col gap-4" key={items}>
                                        <Image
                                            loader={myLoader}
                                            src={placeholder}
                                            alt="Placeholder"
                                            width={500}
                                            height={500}
                                        />
                                        <p>Skill</p>
                                    </div>
                                ))
                            }

                        </div>
                    </section>

                    <section className="flex flex-col gap-5">
                    <div className="flex flex-col gap-3 items-center">
                            <h1 className="text-3xl md:text-5xl text-black">Clients</h1>
                            <hr className="w-1/6 text-red-800 border-2 border-red-800" />
                        </div>
                    </section>

                    <section className="flex flex-col gap-4 flex-wrap">
                        {/* Shops */}
                        <Shop />

                        {/* Work */}
                        <Work />

                        {/* Project */}
                        <Project />

                        {/* Message */}
                        <Message />

                    </section>
                    <section>
                        <Social />
                    </section>
                </section>

                <Footer />
            </main>
        </>
    );
}

export default Yonas;
